// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	ports "github.com/guil95/ports/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// FileReader is an autogenerated mock type for the FileReader type
type FileReader struct {
	mock.Mock
}

// ReadFileStream provides a mock function with given fields: path, port, quit
func (_m *FileReader) ReadFileStream(path string, port chan ports.Ports, quit chan error) {
	_m.Called(path, port, quit)
}

type mockConstructorTestingTNewFileReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileReader creates a new instance of FileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileReader(t mockConstructorTestingTNewFileReader) *FileReader {
	mock := &FileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
