// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/guil95/ports/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByIdempotencyID provides a mock function with given fields: ctx, idempotencyID
func (_m *Repository) FindByIdempotencyID(ctx context.Context, idempotencyID string) (*ports.Ports, error) {
	ret := _m.Called(ctx, idempotencyID)

	var r0 *ports.Ports
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.Ports); ok {
		r0 = rf(ctx, idempotencyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.Ports)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idempotencyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SavePort provides a mock function with given fields: ctx, _a1
func (_m *Repository) SavePort(ctx context.Context, _a1 *ports.Ports) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ports.Ports) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePort provides a mock function with given fields: ctx, _a1
func (_m *Repository) UpdatePort(ctx context.Context, _a1 *ports.Ports) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ports.Ports) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
